import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.scss";
import { Separator } from "../components/Separator";
import { trpc } from "../utils/trpc";
import { ToDoInput } from "../features/ToDo/components/ToDoInput";
import { ToDoItem } from "../features/ToDo/components/ToDoItem";

export default function Home() {
  const toDos = trpc.toDo.get.useQuery();

  const renderToDoItems = () => {
    if (!toDos.data) {
      return <div>Loading...</div>;
    }

    const remainingToDos = toDos.data.filter(({ completed }) => !completed);

    if (!remainingToDos.length) {
      return <div>All done - GZ!</div>;
    }


    return remainingToDos.map(({ id, label, completed }) => (
      <ToDoItem key={id} id={id} checked={completed} text={label} />
    ));
  };

  const renderCompletedToDos = () => {
    if (!toDos.data) return;

    const completedToDos = toDos.data.filter(({ completed }) => completed);

    if (!completedToDos.length) return;

    return (
      <>
        <h2 className={styles.header}>Done 🛌</h2>

        <div className={styles.toDoContainer}>
          <Separator />
          {completedToDos.map(({ id, label, completed }) => (
            <ToDoItem key={id} id={id} checked={completed} text={label} />
          ))}
        </div>
      </>
    );
  };

  return (
    <>
      <Head>
        <title>So much TODO!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.header}>To-do list 🎉</h1>

        <Separator />

        <div className={styles.toDoContainer}>
          {renderToDoItems()}
          <ToDoInput />
        </div>

        {renderCompletedToDos()}
      </main>
    </>
  );
}
